### ISSUE TITLE
private method `mkdir' called on File (Class)

### ISSUE THREAD

**Issue by jjuarez** [DAddYE/do#1]
kernel/delta/kernel.rb:79:in `mkdir (method_missing)'
/Users/jjuarez/.rvm/gems/rbx-master/gems/do-0.0.2/lib/do/common.rb:35:in`**script**'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/task.rb:205:in `execute'
kernel/bootstrap/array.rb:76:in`each'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/Users/jjuarez/.rvm/rubies/rbx-master/lib/monitor.rb:191:in `synchronize (mon_synchronize)'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/application.rb:112:in`invoke_task'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
kernel/bootstrap/array.rb:76:in`each'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/Users/jjuarez/.rvm/gems/rbx-master/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/jjuarez/.rvm/gems/rbx-master/gems/do-0.0.2/bin/doit:30:in`**script**'
kernel/common/kernel.rb:732:in `load'
/Users/jjuarez/.rvm/gems/rbx-master/bin/doit:19:in`**script**'
kernel/delta/codeloader.rb:65:in `load_script'
kernel/delta/codeloader.rb:90:in`load_script'
kernel/loader.rb:618:in `script'
kernel/loader.rb:762:in`main'
Tasks: TOP => setup

**Comment by rfelix** [comment]
I also got the same error, with both local Ruby 1.8.7 on OSX and on 1.9.2 via RVM.

**Comment by DAddYE** [comment]
Thanks! Released 0.0.3 version!
